import { Metadata } from "next";
import TrainingNavBar from "./TrainingNavbar";
// import { ErrorWrapper } from "./error-wrapper";

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - Codevolution",
    template: "%s | Codevolution",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <TrainingNavBar></TrainingNavBar>
        </header>
        {/* <ErrorWrapper> */}
        {children}
        {/* </ErrorWrapper> */}
        <footer>
          <p>Training Footer</p>
        </footer>
      </body>
    </html>
  );
}
